version: '3'

services:
    web:
        build: .
        command: python web2.py
        ports:
            - "80:80"
        volumes:
            - .:/app
        networks:
            - network
    web2:
        build: ./another
        command: python app.py
        ports:
            - "81:5000"
        networks:
            - network

networks:
    network: